steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ecclesia-app:$SHORT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ecclesia-app:$SHORT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ecclesia-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ecclesia-app:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production,NEXT_PUBLIC_FIREBASE_PROJECT_ID=$PROJECT_ID,FIREBASE_ADMIN_PROJECT_ID=$PROJECT_ID'
      - '--set-secrets'
      - 'NEXTAUTH_SECRET=nextauth-secret:latest,OPENAI_API_KEY=openai-key:latest'

images:
  - 'gcr.io/$PROJECT_ID/ecclesia-app:$SHORT_SHA'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

