export const plans = [
  {
    name: 'Free',
    price: '$0',
    period: '/month',
    description: 'Perfect for small churches getting started',
    features: [
      'Up to 50 members',
      'Basic member management',
      'Community feed',
      'Prayer wall',
      'Basic event calendar',
      'Email support',
    ],
    cta: 'Start Free',
    popular: false,
  },
  {
    name: 'Basic',
    price: '$49',
    period: '/month',
    description: 'For growing churches',
    features: [
      'Up to 200 members',
      'All Free features',
      'AI Discipleship',
      'Sermon Hub',
      'Giving & Finance',
      'Event registration',
      'Priority support',
    ],
    cta: 'Get Started',
    popular: true,
  },
  {
    name: 'Pro',
    price: '$99',
    period: '/month',
    description: 'For established churches',
    features: [
      'Up to 1,000 members',
      'All Basic features',
      'Payroll system',
      'Advanced analytics',
      'Gamification',
      'Custom branding',
      '24/7 support',
    ],
    cta: 'Get Started',
    popular: false,
  },
  {
    name: 'Enterprise',
    price: 'Custom',
    period: '',
    description: 'For large organizations',
    features: [
      'Unlimited members',
      'All Pro features',
      'Multi-church management',
      'Dedicated support',
      'Custom integrations',
      'SLA guarantee',
      'Training & onboarding',
    ],
    cta: 'Contact Sales',
    popular: false,
  },
]

